services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      # Change this line
      - "1434:1433" 
    volumes:
      # Also, fix a small typo here: /varopt/mssql should be /var/opt/mssql
      # This ensures your data is saved correctly.
      - sql-data:/var/opt/mssql 
volumes:
  sql-data: